[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PRIVATE_TARGET = "server"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[forms]
  [forms."contact"]
    email = "guewoljohannkionghat@gmail.com"

[forms.contact.notifications]
  [[forms.contact.notifications.email]]
    to = "guewoljohannkionghat@gmail.com"
    from = "noreply@edumatch.fr"
    subject = "Nouveau message de contact EduMatch"
    template = """
Nouveau message de contact reçu :

Nom : {{name}}
Email : {{email}}
Message : {{message}}

---
Envoyé depuis le formulaire de contact EduMatch
"""

[functions]
  external_node_modules = ["@netlify/plugin-nextjs"]
