[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18.17.0"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  external_node_modules = ["@netlify/plugin-nextjs"]
